import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'
import Sidebar from '@/components/Sidebar'
import Header from '@/components/Header'
import Footer from '@/components/Footer/Footer'
import MobileMenu from '@/components/MobileMenu'

const poppins = Poppins({
   subsets: ['latin'],
   weight: ['400', '500', '600', '700'],
})

export const metadata: Metadata = {
   title: 'Casino',
   description: 'Generated by create next app',
}

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode
}>) {
   return (
      <html lang='en'>
         <body className={`${poppins.className} antialiased min-h-screen`}>
            <Sidebar />
            <Header />
            <main className='mx-[10px] max-w-[1220px] main-centered-lg mt-[15px] lg:px-2.5'>{children}</main>
            <Footer />
            <MobileMenu />
         </body>
      </html>
   )
}
